### ISSUE TITLE
Polaris CI is failing

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb-iceberg#256]
Looking through the Polaris repo pull request history, https://github.com/apache/polaris/pull/1532 seems to be the culprit
We should probably look at the way their version of the authorization getting-started example has evolved to deal with this change

**Comment by Tishj** [comment]
```sh
./polaris \
  --client-id root \
  --client-secret secret \
  catalogs \
  create \
  --storage-type FILE \
  --default-base-location file://${PWD}/storage_files \
  quickstart_catalog
```

```
Exception when communicating with the Polaris server. IllegalArgumentException: Unsupported storage type: FILE
Exception when communicating with the Polaris server. NotFoundException: TopLevelEntity of type CATALOG does not exist: quickstart_catalog
Exception when communicating with the Polaris server. NotFoundException: Entity quickstart_catalog not found when trying to assign quickstart_catalog.quickstart_catalog_role to quickstart_user_role
Exception when communicating with the Polaris server. NotFoundException: Catalog not found: quickstart_catalog
```

In that script (`scripts/polaris/setup_polaris_catalog.sh`) there is mention of a python module
Perhaps we want to see if that's available now and can make this initialization more future-proof ?

**Comment by Tishj** [comment]
From their own docker-compose.yml file that's checked in:
```yml
    environment:
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
      AZURE_TENANT_ID: $AZURE_TENANT_ID
      AZURE_CLIENT_ID: $AZURE_CLIENT_ID
      AZURE_CLIENT_SECRET: $AZURE_CLIENT_SECRET
      POLARIS_BOOTSTRAP_CREDENTIALS: POLARIS,root,secret
      quarkus.log.file.enable: "false"
      quarkus.otel.sdk.disabled: "true"
      polaris.features."ALLOW_INSECURE_STORAGE_TYPES": "true"
      polaris.features."SUPPORTED_CATALOG_STORAGE_TYPES": "[\"FILE\",\"S3\",\"GCS\",\"AZURE\"]"
      polaris.readiness.ignore-severe-issues: "true"
```

These are probably interesting for us:
```
      polaris.features."ALLOW_INSECURE_STORAGE_TYPES": "true"
      polaris.features."SUPPORTED_CATALOG_STORAGE_TYPES": "[\"FILE\",\"S3\",\"GCS\",\"AZURE\"]"
```

also these might be interesting
```
      POLARIS_BOOTSTRAP_CREDENTIALS: POLARIS,root,secret
      polaris.readiness.ignore-severe-issues: "true"
```
